version: '3'
services:

#  brick-db:
#    image: library/mysql:8.0.23
#    container_name: brick-db
#    restart: always
#    command: # 명령어 실행 한글 깨짐 방지
#      - --character-set-server=utf8mb4
#      - --collation-server=utf8mb4_unicode_ci
#    ports:
#      - 3306:3306 # 호스트 : 컨테이너
#    environment:
#      MYSQL_ROOT_PASSWORD: root # 초기비밀번호
#      TZ: Asia/Seoul
#    volumes:
#      - ./db/mysql/data:/var/lib/mysql # 디렉토리 마운트 설정

  brick-proxy:
    container_name: brick-proxy
    image: lsyeup1206/brick-proxy
    ports:
      - 80:80
    depends_on:
      - brick-server
    environment:
      TZ: "Asia/Seoul"

  brick-server:
    container_name: brick-server
    image: lsyeup1206/brick-server
    volumes:
      - type: bind
        source: ./log
        target: /home/logs/brick-server-log
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      TZ: "Asia/Seoul"

#  brick-db:
#    platform: linux/x86_64
#    image: mysql:8.0.17
#    container_name: brick-db
#    restart: always
#    ports:
#      - 3306:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      TZ: Asia/Seoul
#    command:
#      - --character-set-server=utf8mb4
#      - --collation-server=utf8mb4_unicode_ci
#    volumes:
#      - ./mysql8/db:/var/lib/mysql
#      - ./mysql8/config:/etc/mysql
#      - ./mysql8/mysql-files:/var/lib/mysql-files